### ISSUE TITLE
Migration Doc: In `listRooms` response, field `creationTime` has been changed from Int to BigInt

### ISSUE THREAD

**Issue by punitsu** [livekit/node-sdks#154]
Change commit: https://github.com/livekit/server-sdk-js/commit/8cad1ba05618d2f43c5f4397bce30552ce30ebca#diff-220adc3013305af91ae2598008e4b021fecda4a13c905830f622a7ab0f09d63fL169

 listRooms response, field creationTime has been changed from Int to BigInt. I couldn't find any doc or changelog for this.

**Comment by lukasIO** [comment]
thanks for pointing that out, what docs would you like to see around this?
