### ISSUE TITLE
Issue with Parallel Room Instances and Audio Publishing

### ISSUE THREAD

**Issue by vlxdisluv** [livekit/node-sdks#227]
Hi,

When running two instances of a room in parallel, the second instance stops publishing audio after the first instance completes its execution and calls the await room.disconnect() method, even though these are two separate, independent room instances. The issue occurs as follows snippet from example:
```
const room = new Room();
await room.connect(process.env.LIVEKIT_URL, jwt, { autoSubscribe: true, dynacast: true });

const sample = readFileSync(join(process.cwd(), './speex.wav'));
const channels = sample.readUInt16LE(22);
const sampleRate = sample.readUInt32LE(24);
const dataSize = sample.readUInt32LE(40) / 2;

const source = new AudioSource(sampleRate, channels);
const track = LocalAudioTrack.createAudioTrack('audio', source);
const options = new TrackPublishOptions();
const buffer = new Int16Array(sample.buffer);
options.source = TrackSource.SOURCE_MICROPHONE;
await room.localParticipant.publishTrack(track, options);
await new Promise((resolve) => setTimeout(resolve, 1000)); // wait a bit so the start doesn't cut off

let written = 44; // start of WAVE data stream
const FRAME_DURATION = 1; // write 1s of audio at a time
const numSamples = sampleRate / FRAME_DURATION;
while (written < dataSize) {
  const available = dataSize - written;
  const frameSize = Math.min(numSamples, available);

  const frame = new AudioFrame(
    buffer.slice(written, written + frameSize),
    sampleRate,
    channels,
    Math.trunc(frameSize / channels),
  );
  await source.captureFrame(frame);

  written += frameSize;
}

await room.disconnect();
```

Steps to Reproduce:

- Run the above script to set up and connect two independent room instances in parallel.
- Ensure both instances start publishing audio.
- Let the first instance complete.
- Observe that the second instance stops publishing audio to the room.

Node.js package version:
@livekit/rtc-node: 0.5.0

**Comment by vlxdisluv** [comment]
@theomonnom thanks for fix. 

Could I also ask about dispose()? Should I utilize it after each audio publishing is done, or only when process.on('SIGINT') is triggered?

**Comment by theomonnom** [comment]
> Could I also ask about dispose()? Should I utilize it after each audio publishing is done, or only when process.on('SIGINT') is triggered? Sometimes, when I call this method, I encounter the error Error: trying to drop an invalid handle, which crashes the server.

dispose() is definitely confusing, we plan to remove it in the future versions (no need to call any function, just room.disconnect).

For now, you're right, you should only call it when the program ends
