### ISSUE TITLE
IO error: invalid peer certificate: UnknownIssuer

### ISSUE THREAD

**Issue by vlxdisluv** [livekit/node-sdks#238]
**Problem**

When attempting to connect to a room using the @livekit/rtc-node library, I encounter an error on the staging environment, while it works fine locally.

**Code**

```
import { Room } from '@livekit/rtc-node';

const room = new Room();
await room.connect(this.options.host, jwtToken, { autoSubscribe: true, dynacast:
```

**Error**

```
{
   "type": "ConnectError",
   "message": "engine: signal failure: ws failure: IO error: invalid peer certificate: UnknownIssuer",
   "stack": "Error: engine: signal failure: ws failure: IO error: invalid peer certificate: UnknownIssuer\n    at Room.connect (file:///usr/src/app/node_modules/@livekit/rtc-node/dist/room.js:202:19)\n "
},
```
---------
**Environment**

- Library version: @livekit/rtc-node ^0.5.0
- Node.js version: v22.4.1
- Livekit Server version: v1.7 (both locally and on staging)
- Environment: Staging
- Works locally without issues
- Steps to Reproduce

**Steps to Reproduce**

1. Use the provided code snippet to connect to a room.
2. Deploy the code to the staging environment.
3. Attempt to connect to the room.

**Comment by davidzhao** [comment]
Do you have CA root certs installed on your server environment? On Debian based servers, it's [ca-certificates](https://packages.debian.org/search?keywords=ca-certificates) pkg

**Comment by vlxdisluv** [comment]
> Do you have CA root certs installed on your server environment? On Debian based servers, it's [ca-certificates](https://packages.debian.org/search?keywords=ca-certificates) pkg

Thanks for answer. 

Yes, I do, but it was an old version. After updating, the problem was resolved. Thanks!

**Comment by brian-collins-af** [comment]
What about windows server with NodeJS how to i update the certificates for NodeJS
