### ISSUE TITLE
How do I publish my voice microphone to Livekit?

### ISSUE THREAD

**Issue by KevinAdhaikal** [livekit/node-sdks#270]
Hello, how do I publish my microphone voice to the Livekit? do you have any examples?

Sorry if my grammar is bad

**Comment by davidzhao** [comment]
You'd want to use one of the client SDKs. please refer to these quickstarts: https://docs.livekit.io/realtime/quickstarts/

Currently node.js, a backend SDK, cannot publish from mic/camera
